targets:
  $default:
    builders:
      # disables the SharedPartBuilder in favor of a PartBuilder from moor_generator
      moor_generator:
        enabled: false
      moor_generator|moor_generator_not_shared:
        enabled: true

      # Run built_value_generator when moor is done!
      built_value_generator|built_value:
        enabled: false
  
  run_built_value:
    dependencies: ['with_built_value']
    builders:
      # Disable all auto-applied builders from moor
      moor_generator:
        enabled: false
      moor_generator|preparing_builder:
        enabled: false